[package]
name = "tlrepo"
version = "0.1.0"
authors = ["Josh Triplett <josh@joshtriplett.org>"]
description = "Thread-local git2::Repository, shareable across threads"
repository = "https://github.com/joshtriplett/tlrepo"
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
git2 = { version = "0.13.5", default-features = false }
thread_local = "1.0.1"
